import type { Metadata } from "next";
import Link from "next/link";
import { ArrowDownToLine, ArrowRight, Box, ChevronDown, Clock3, MessageSquareText, Package, Phone, Search } from "lucide-react";
import { notFound } from "next/navigation";
import { Footer } from "@/components/Footer";
import { Benefits } from "@/components/Benefits";
import { OrderButton } from "@/components/SiteDrawer";
import { ProductArt, type ProductShape } from "@/components/ProductArt";
import { categories, categoryBySlug, formatPrice, productBySlug, products, type Product } from "@/lib/catalog";
import styles from "../catalog.module.css";

export function generateStaticParams() { return [...categories.map(({slug})=>({slug})),...products.map(({slug})=>({slug}))]; }
export async function generateMetadata({params}:{params:Promise<{slug:string}>}):Promise<Metadata>{const {slug}=await params;const category=categoryBySlug(slug);const product=productBySlug(slug);if(category)return{title:category.title,description:`${category.description}. Актуальные остатки и быстрая доставка.`};if(product)return{title:product.name,description:`${product.subtitle}. Артикул ${product.article}.`};return{};}

function Stock({product}:{product:Product}) { return <span className={`${styles.stock} ${product.stock<=5?styles.low:""}`}><i/>{product.stock?`В наличии: ${product.stock} шт.`:"Под заказ"}</span>; }
function Crumbs({last,category}:{last:string;category?:string}) { return <nav className={styles.crumbs} aria-label="Хлебные крошки"><Link href="/">Главная</Link><span>/</span><Link href="/catalog">Каталог</Link>{category&&<><span>/</span><Link href={`/catalog/${category}`}>Пластины</Link></>}<span>/</span><b>{last}</b></nav>; }
function ProductCard({product}:{product:Product}) { return <Link className={styles.productCard} href={`/catalog/${product.slug}`}><div className={styles.productVisual}><ProductArt shape={product.shape}/></div><h3>{product.name}</h3><p>{product.subtitle}</p><small>{product.specs.Длина||"58 мм"}　·　{product.specs["Количество отверстий"]||"6 отв."}　·　сталь</small><strong>{formatPrice(product.price)}</strong><Stock product={product}/><span className={styles.more}>Подробнее <ArrowRight/></span></Link>; }

export default async function CatalogSlugPage({params}:{params:Promise<{slug:string}>}) {
  const {slug}=await params; const category=categoryBySlug(slug); const product=productBySlug(slug); if(!category&&!product)notFound();
  if(category){
    const source=products.filter((item)=>item.category===category.slug); const display=source.length>=8?source:Array.from({length:8},(_,i)=>source[i%source.length]||products[i%products.length]);
    const shapes:{title:string,count:string,shape:ProductShape}[]=[{title:"Прямые",count:"46 товаров",shape:"plate"},{title:"Т-образные",count:"27 товаров",shape:"tplate"},{title:"L-образные",count:"16 товаров",shape:"lplate"},{title:"Реконструктивные",count:"12 товаров",shape:"plate"},{title:"Для бедренной кости",count:"9 товаров",shape:"plate"},{title:"Для таза",count:"7 товаров",shape:"tplate"}];
    return <main id="main" className="page-main"><div className="site-shell"><Crumbs last={category.title}/><section className={styles.categoryHero}><div><h1>{category.title} для<br/>остеосинтеза</h1><p>{category.description}.<br/>Актуальное наличие и доставка по Воронежу<br/>за 2–4 часа.</p><div className={styles.miniBenefits}><span><Clock3/><b>2–4 часа</b><small>доставка по Воронежу</small></span><span><Box/><b>Остаток в реальном времени</b><small>до оформления заказа</small></span></div></div><div className={styles.heroProduct}><ProductArt shape={category.art==="plate"?"tplate":category.art as ProductShape}/></div></section>
      <section className={styles.subcategories}>{shapes.map((item)=><button key={item.title}><ProductArt shape={item.shape}/><b>{item.title}</b><span>{item.count}</span></button>)}<button><Package/><b>Все {category.title.toLowerCase()}</b><span>{category.count}</span></button></section>
      <section className={styles.catalogLayout}><aside className={styles.filters}><div><h2>Фильтры</h2><button>Сбросить все</button></div><label><b>Наличие</b><span><input type="checkbox" defaultChecked/>В наличии <small>127</small></span><span><input type="checkbox"/>Под заказ <small>24</small></span></label>{["Форма пластины","Длина, мм","Ширина, мм","Количество отверстий","Материал","Цена, ₽"].map((name)=><button className={styles.filterRow} key={name}>{name}<ChevronDown/></button>)}</aside><div className={styles.catalogMain}><div className={styles.catalogTop}><h2>127 товаров</h2><label><Search/><input placeholder="Поиск по каталогу"/></label><button>Сначала популярные <ChevronDown/></button></div><div className={styles.chips}><span>В наличии　×</span><span>Длина 58–85 мм　×</span><span>6 отверстий　×</span><button>Сбросить всё</button></div><div className={styles.productGrid}>{display.map((item,index)=><ProductCard product={{...item,slug:index<source.length?item.slug:`${item.slug}?variant=${index}`}} key={`${item.slug}-${index}`}/>)}</div></div></section>
      <section className={styles.catalogCta}><div><h2>Нужна пластина сегодня?</h2><p>Отправьте параметры или фото назначения.<br/>Мы проверим склад и подберём подходящий вариант.</p><Link className="primary-button" href="/contacts">Написать специалисту <ArrowRight/></Link></div><ProductArt shape="set"/></section><div className={styles.pagination}><button>‹</button><b>1</b><span>2</span><span>3</span><span>…</span><span>9</span><button>›</button></div><section className={styles.bottomHelp}><MessageSquareText/><div><b>Не нашли нужную форму или размер?</b><span>Сообщите параметры — проверим склад и подберём аналог</span></div><Link className="primary-button" href="/contacts">Проверить наличие <ArrowRight/></Link></section></div><Footer/></main>;
  }
  if(!product)notFound();
  const related=products.filter((item)=>item.category===product.category&&item.slug!==product.slug).slice(0,4);
  const keySpecOrder = ["Длина", "Количество отверстий", "Ширина", "Толщина", "Материал"];
  return <main id="main" className="page-main"><div className="site-shell"><Crumbs last={`${product.name} ${product.specs.Длина||""}`} category={product.category}/><section className={styles.detail}><div><div className={styles.galleryMain}><button aria-label="Увеличить изображение"><Search/></button><ProductArt shape={product.shape}/></div><div className={styles.thumbs}>{[product.shape,"plate","lplate","tplate"].map((shape,i)=><button className={i===0?styles.selected:""} key={`${shape}-${i}`}><ProductArt shape={shape as ProductShape}/></button>)}</div></div><div className={styles.detailCopy}><div className={styles.stockLine}><Stock product={product}/><span>Артикул: {product.article}</span></div><h1>{product.name}</h1><p>{product.subtitle}.</p><div className={styles.keySpecs}>{keySpecOrder.map((key)=><span key={key}><b>{product.specs[key]||"Сталь"}</b><small>{key.toLowerCase()}</small></span>)}</div><strong className={styles.bigPrice}>{formatPrice(product.price)}</strong><p className={styles.deliveryNote}><Clock3/>Доставим по Воронежу сегодня за 2–4 часа</p><OrderButton product={product} className={styles.orderButton}/><a className={styles.phone} href="tel:+79611898933"><Phone/>+7 (961) 189–89–33</a></div></section>
      <section className={styles.variants}><h2>Выберите<br/>вариант</h2><div><b>Длина</b><span>{["33 мм","47 мм","58 мм","70 мм","85 мм"].map(v=><button className={v===(product.specs.Длина||"58 мм")?styles.on:""} key={v}>{v}</button>)}</span></div><div><b>Количество отверстий</b><span>{["4 отв.","6 отв.","8 отв.","10 отв."].map(v=><button className={v.startsWith(product.specs["Количество отверстий"]||"6")?styles.on:""} key={v}>{v}</button>)}</span></div><div><b>Ширина</b><span>{["4,5 мм","6 мм","10 мм"].map(v=><button className={v===(product.specs.Ширина||"6 мм")?styles.on:""} key={v}>{v}</button>)}</span></div></section><Benefits compact/>
      <section className={styles.specBlocks}><article><h2>Характеристики</h2><h3>Основные параметры</h3><dl>{Object.entries(product.specs).map(([key,value])=><div key={key}><dt>{key}</dt><dd>{value}</dd></div>)}</dl><button className="secondary-button">Скачать техническую документацию <ArrowDownToLine/></button></article><article><h2>Размерная схема</h2><ProductArt shape={product.shape}/><a href="#">Все размеры в PDF <ArrowDownToLine/></a></article></section>
      <section className={styles.related}><div><h2>Для установки этой пластины</h2><Link href="/catalog">Смотреть все <ArrowRight/></Link></div><div>{[products.find(p=>p.category==="screws"),products.find(p=>p.category==="tools"),products.find(p=>p.category==="sets"),...related].filter(Boolean).slice(0,4).map((item)=><ProductCard product={item!} key={item!.slug}/>)}</div></section><section className={styles.bottomHelp}><MessageSquareText/><div><b>Не нашли нужную форму или размер?</b><span>Сообщите параметры — проверим склад и подберём аналог</span></div><Link className="primary-button" href="/contacts">Проверить наличие <ArrowRight/></Link></section></div><Footer/></main>;
}
